---
- hosts: all
  name: Install repository
  become: true
  gather_facts: false

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - ansible.builtin.wait_for_connection:
      delay: 5
      timeout: 600

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: Initialize the user defined variables
      set_fact:
        enable_edb_repo: false

    - name: Create {{ pg_owner }} OS user
      ansible.builtin.user:
        name: "{{ pg_owner }}"

  roles:
    - role: setup_repo

- hosts: dbt2_driver
  name: Install DBT2 driver
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Create {{ pg_owner }} OS user
      ansible.builtin.user:
        name: "{{ pg_owner }}"

  roles:
    - role: setup_dbt2_driver

  tasks:
    - name: Update /var/lib/pgsql/.pgpass
      ansible.builtin.lineinfile:
        path: "{{ pg_user_home }}/.pgpass"
        regexp: ^\*:\*:\*:{{ pg_owner }}.*
        line: "*:*:*:{{ pg_owner }}:{{ pg_password }}"
        owner: "{{ pg_owner }}"
        group: "{{ pg_group }}"
        mode: "0600"
      become: true
