---
- hosts: all
  name: Install repository
  become: true
  gather_facts: false

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - ansible.builtin.wait_for_connection:
      delay: 5
      timeout: 600

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: Create {{ pg_owner }} OS user
      ansible.builtin.user:
        name: "{{ pg_owner }}"
      when: inventory_hostname not in groups['primary']

  roles:
    - role: setup_repo

- hosts: dbt2_driver
  name: Install DBT2 driver
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Create {{ pg_owner }} OS user
      ansible.builtin.user:
        name: "{{ pg_owner }}"

  roles:
    - role: setup_dbt2_driver

  tasks:
    - name: Update .pgpass
      ansible.builtin.lineinfile:
        path: "{{ pg_user_home }}/.pgpass"
        regexp: ^\*:\*:\*:{{ pg_owner }}.*
        line: "*:*:*:{{ pg_owner }}:{{ pg_password }}"
        owner: "{{ pg_owner }}"
        group: "{{ pg_group }}"
        mode: "0600"
      become: true

- hosts: primary
  name: Install PostgreSQL
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  roles:
    - install_dbserver
    - init_dbserver
    - manage_dbserver
    - setup_dbt2
    - setup_touchstone_tools
